### ISSUE TITLE
Any news about this project

### ISSUE THREAD

**Issue by aurelbdx** [svp318/MSFS2020-Real-Time-Weather#1]
Is there any news about this project ? I like it!!
I would like precipitations in the preset

**Comment by svp318** [comment]
Hey! I just released a new version which now includes precipitation and thunderstorm information in the preset. There are still many other stuff pending like wind gust data, and the option to save the preset somewhere else, as right now it works with the Steam version, which is what I have.

Sorry for taking so long, I can only work on this project when I'm not busy with other stuff. Thanks for the support!

**Comment by aurelbdx** [comment]
Thanks :)
